# this will be overridden by github but is useful for testing and CI
# pipelines
source: 'sphinx/_build/html'
destination: 'site'

# include the sphinx assets jekyll usually ignores
include: [
      '_images',
      '_sources',
      '_static',
]
  

