line-length = 88
select = ["E", "F", "B",] # To add: "S" for security, but this adds a lot of things that aren't too relevant
ignore = ["E203", "E501", "E266",]

[per-file-ignores]
"noxfile.py" = ["E402"]

# ignore "pythonic" comparisons to booleans, for clarity in writing tests
"tests/*" = ["S101", "S603", "B011", "E712"]
