global:
  scrape_interval:     1s 
  evaluation_interval: 1s 

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  # - job_name: 'self'
  #   static_configs:
  #   - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'nvidia_gpu_exporter'
    static_configs:
    - targets: ['localhost:9445']

  - job_name: 'job1'

    static_configs:
    - targets: ['localhost:9001']
