## exporter ports
# node_exporter: 9100
# gpu_exporter: 9445
# python_client: 9001

## local subrange node idxs
# node_exporter: 0
# gpu_exporter: 1
# python client: 2

# pre-allocated targets
# job0: 10000, 10001, 10002
# job1: 10010, 10011, 10012
# job2: ...
# job3: ...
# job4: ...
# job5: ...
# job6: ...
# job7: ...
# job8: ...
# job9: ...

prefix="-F $HOME/.ssh/config -J hpcc.dev"

[tunnels]

job0 = "ssh -N -F $HOME/.ssh/config -J hpcc.dev -L 50000:localhost:9100 -L 50001:localhost:9445 -L 50002:localhost:9001 lotzsamu@lac-025"

job1 = "ssh -N -F $HOME/.ssh/config -J hpcc.dev -L 50010:localhost:9100 -L 50011:localhost:9445 -L 50012:localhost:9001 lotzsamu@lac-027"


# "${prefix} -L 50020:localhost:9100 -L 50021:localhost:9445 -L 50022:localhost:9001 node" # job2
# "${prefix} -L 50030:localhost:9100 -L 50031:localhost:9445 -L 50032:localhost:9001 node" # job3
# "${prefix} -L 50040:localhost:9100 -L 50041:localhost:9445 -L 50042:localhost:9001 node" # job4
# "${prefix} -L 50050:localhost:9100 -L 50051:localhost:9445 -L 50052:localhost:9001 node" # job5
# "${prefix} -L 50060:localhost:9100 -L 50061:localhost:9445 -L 50062:localhost:9001 node" # job6
# "${prefix} -L 50070:localhost:9100 -L 50071:localhost:9445 -L 50072:localhost:9001 node" # job7
# "${prefix} -L 50080:localhost:9100 -L 50081:localhost:9445 -L 50082:localhost:9001 node" # job8
# "${prefix} -L 50090:localhost:9100 -L 50091:localhost:9445 -L 50092:localhost:9001 node" # job9

