version: '3'

# persistent volumes used for saving the data of the containers
volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  
  prometheus:
    
    build:
      context: ./containers/prometheus
      dockerfile: Containerfile
        
    ports:
      - 9090:9090

    # user: "1000"

    network_mode: "host"

    volumes:
      - ./volumes/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
      # - ./volumes/prometheus/alert.rules:/etc/prometheus/alert.rules

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

    # restart: always

  grafana:
    
    build:
      context: ./containers/grafana
      dockerfile: Containerfile
        
    depends_on:
      - prometheus
        
    ports:
      - 3000:3000

    network_mode: "host"

    # user: "1000:1000"
      
    volumes:
      - ./volumes/grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana

    env_file:
      - ./envs/grafana/env.sh

    # restart: always

  # alertmanager:
  #   build:
  #     context: ./containers/alertmanager
  #     dockerfile: Containerfile
        
  #   ports:
  #     - 9093:9093

  #   # user: "1000:1000"

  #   volumes:
  #     - ./volumes/alertmanager/:/etc/alertmanager/
      
  #   network_mode: "host"

  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
  
