package:
  name: fshank
  version: 2020-03-09a0.dev0

source:
  fn: fshank-2020-03-09a0.dev0.tar.gz
  url: https://github.com/salotz/fshank/releases/download//{{ version }}/{{ name }}-{{ version }}.tar.gz
  # TODO: way to specify a hole or 
  sha256:

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - fshank = fshank.cli:cli

requirements:
  build:
    - python
    - setuptools
    - wheel

  host:
    - python
    
  run:
    - python
    

about:
  home: https://github.com/salotz/fshank
  license: GPLv3
  license_file: LICENSE
  summary: "Read, write, and manipulate fshank files"
  doc_url: https://salotz.github.io/fshank
  dev_url: https://github.com/salotz/fshank

extra:
  recipe-maintainers:
    - salotz
