package:
  name: wepy
  version: 1.0.0rc

source:
  fn: wepy-1.0.0.tar.gz
  url: https://pypi.io/packages/source/w/wepy/wepy-1.0.0.tar.gz
  sha256:

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - wepy = wepy.cli:cli

requirements:
  build:
    - python
    - setuptools
    - wheel
    - cython
    - numpy
    - pytest-runner

  host:
    - python
    - pip

  run:
    - python
    

about:
  home: https://github.com/adicksonlab/wepy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Weighted ensemble (WE) framework for Python"
  doc_url: https://adicksonlab.github.io/wepy/
  dev_url: https://github.com/adicksonlab/wepy

extra:
  recipe-maintainers:
    - salotz
