{
 "title": "Nvidia GPU Copy",
 "description": "GPU dashboard for nvidia metrics ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "gpu_exporter_job", "label": "gpu_exporter_job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "prom_job: $gpu_exporter_job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "gpu_exporter_job" },
  {
   "title": "# GPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_num_devices{job=\"$gpu_exporter_job\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_duty_cycle{job=\"$gpu_exporter_job\"}) / sum(nvidia_gpu_num_devices{job=\"$gpu_exporter_job\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes{job=\"$gpu_exporter_job\"}) / sum(nvidia_gpu_num_devices{job=\"$gpu_exporter_job\"})"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle{job=\"$gpu_exporter_job\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes{job=\"$gpu_exporter_job\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 } },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_power_usage_milliwatts{job=\"$gpu_exporter_job\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_temperature_celsius{job=\"$gpu_exporter_job\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_fanspeed_percent{job=\"$gpu_exporter_job\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  }
 ]
}