{
 "title": "Python Process 2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "py_proc", "label": "py_proc", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "Process Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$py_proc\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job=\"$py_proc\"}"
    }
   ]
  },
  {
   "title": "PyGC Total Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "python_gc_collections_total{job=\"$py_proc\"}"
    }
   ]
  },
  {
   "title": "PyGC Collected Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{job=\"$py_proc\"}"
    }
   ]
  }
 ]
}