version: '3'

services:
  
  prometheus:
    build:
      context: ./containers/prometheus
      dockerfile: Containerfile
        
    ports:
      - 9090:9090

    network_mode: "host"

    volumes:
      - ./volumes/prometheus/:/etc/prometheus/

    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    build:
      context: ./containers/alertmanager
      dockerfile: Containerfile
        
    ports:
      - 9093:9093

    volumes:
      - ./volumes/alertmanager/:/etc/alertmanager/
      
    network_mode: "host"

    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    
    build:
      context: ./containers/grafana
      dockerfile: Containerfile
        
    depends_on:
      - prometheus
        
    ports:
      - 3000:3000

    network_mode: "host"

    user: "1000:1000"
      
    volumes:
      - ./volumes/grafana/provisioning/:/etc/grafana/provisioning/
      # - ../../_output/grafana_data:/var/lib/grafana

    env_file:
      - ./envs/grafana/env.sh

    # restart: always
