* Installation Guide

Welcome to the installation guide for wepy. Follow the steps below to
set up the environment and install wepy.

** Prerequisites

Ensure that you are using *Python 3.10*. It is recommended to set up a
conda environment for managing dependencies and ensuring compatibility.

#+BEGIN_SRC bash
    conda create -n wepy-env python=3.10
    conda activate wepy-env
#+END_SRC

** Installing wepy

You can install wepy from the latest git repository.

Installing from Git (for the latest version):

#+BEGIN_SRC bash
    pip install git+https://github.com/ADicksonLab/wepy.git
#+END_SRC

** Installing OpenMM and mdtraj

To install OpenMM, which is highly recommended for running molecular
dynamics simulations:

#+BEGIN_SRC bash
    conda install -c conda-forge openmm=8.0.0
#+END_SRC

If the conda version of openmm doesn't work for your compute
environment, consult the
[[http://docs.openmm.org/latest/userguide/application.html#installing-openmm][OpenMM
documentation]].

The mdtraj library is used by wepy to create and manipulate system
topologies. It can also be installed via conda:

#+BEGIN_SRC bash
    conda install -c conda-forge mdtraj=1.9.9
#+END_SRC

These version numbers work correctly at the time of this writing and
avoid some incompatibility issues with numpy and pandas dependencies.

** Verifying Installation

After installation, you should be able to import wepy in python. Verify
it by running:

#+BEGIN_SRC bash
    python -c "import wepy"
#+END_SRC

If the installation was successful, you should not see any errors.
