
* News and Updates


** Tutorial for Contributors for Running and Writing Examples

<2020-04-29 Wed>

We have a separate repository where we save all the workshops we have
done for the users/contributors in our lab:

[[https://gitlab.com/ADicksonLab/wepy-developer-resources]]

These are topics which may change throughout time, so we don't include
them in the main ~wepy~ tree nor do we guarantee they will work in
perpetuity.

Today we are running a workshop on getting people started running &
writing examples for ~wepy~:

[[https://gitlab.com/ADicksonLab/wepy-developer-resources/-/tree/master/workshops/2020-04-29_Examples-Tutorials-HOWTO][Examples & Tutorials HOWTO]]

In the ~wepy~ project we have a number of utilities which we think
will help us in keeping the examples in our docs up to date with the
code. 

Outdated docs are a frequent problem with software
projects. Hopefully, the strategies that we start to outline here can
help you in all your software projects by gaining a discipline of
carefully maintaining and pinning your dependencies for purpose-driven
virtualenvs.

A common structure for writing examples and tutorials also helps to
allow for automated processes to create and test them in a uniform and
low friction way.

~salotz
