{
 "title": "Wepy Simulation Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reporters Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wepy_reporters_size_bytes" }
   ]
  },
  {
   "title": "Cycles Completed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wepy_cycle_idx_total" }
   ]
  },
  {
   "title": "Simulation Manager Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wepy_sim_manager_size_bytes" }
   ]
  },
  {
   "title": "Single Walker Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wepy_walker_single_size_bytes" }
   ]
  },
  {
   "title": "Work Mapper Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wepy_mapper_size_bytes" }
   ]
  },
  {
   "title": "Walker Ensemble Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "wepy_walker_ensemble_size_bytes"
    }
   ]
  },
  {
   "title": "Boundary Condition Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wepy_bc_size_bytes" }
   ]
  },
  {
   "title": "Runner Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wepy_runner_size_bytes" }
   ]
  },
  {
   "title": "Resampler Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wepy_resampler_size_bytes" }
   ]
  }
 ]
}