name: Quality Checks

on: push

permissions:
  contents: read

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Static analysis
      run: python -m nox -s validate

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Unit Tests
      run: python -m nox -s test_unit
